# Generated by Django 4.1.2 on 2022-10-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_member_username_alter_member_univ_fac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='acadimic_year',
            field=models.CharField(default='L1', max_length=2),
        ),
    ]
