# Generated by Django 4.1.2 on 2022-10-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_member_acadimic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='acadimic_year',
            field=models.IntegerField(default=1),
        ),
    ]
